/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#ifndef FIORDOS6X6_CPARAM_SOLVER_H
#define FIORDOS6X6_CPARAM_SOLVER_H

#ifdef USE_REALTYPE_SINGLE
  typedef float realtype;
#else
  typedef double realtype;
#endif

/* <<< struct Params >>> */
#if defined(USE_PARAMSMODE_PTR)  && !(defined(MATLAB_MEX_FILE) || defined(RT))
#  define PARAMS_MACRO(name,len) const realtype *name;
#else /* the default */
#  define PARAMS_MACRO(name,len) realtype name[len];
#endif
typedef struct {
    PARAMS_MACRO(H,36)
    PARAMS_MACRO(g,6)
    PARAMS_MACRO(Ai,216)
    PARAMS_MACRO(bi,36)
} fiordos6x6_Cparam_Params;
#undef PARAMS_MACRO

/* <<< struct Settings >>> */
typedef struct {
    struct {
        int warmstartInner;
    } approach;
    struct {
        realtype init[6];
        int maxit;
    } algoInner;
    struct {
        realtype init[36];
        int maxit;
    } algoOuter;
} fiordos6x6_Cparam_Settings;

/* <<< struct Result >>> */
typedef struct {
    realtype la[36];
    realtype x[6];
    realtype d;
    int iter;
    int exitflag;
} fiordos6x6_Cparam_Result;

/* <<< struct Work >>> */
typedef struct {
    struct {
        realtype inner_g[6];
        realtype inner_c[1];
        realtype traceH0[1];
    } Prob;
    struct {
        realtype init[6];
        realtype glob_LbL;
        realtype glob_UbL;
        realtype tstep;
        int btnum;
        realtype tstepmin;
        int btstopped;
        realtype res_z[6];
        int res_stopcode;
        int res_iter;
    } algoInner;
    struct {
        realtype init[36];
        realtype glob_LbL;
        realtype glob_UbL;
        realtype tstep;
        int btnum;
        realtype tstepmin;
        int btstopped;
        realtype res_z[36];
        int res_stopcode;
        int res_iter;
    } algoOuter;
} fiordos6x6_Cparam_Work;

/* <<< solver INTERFACE >>> */
void fiordos6x6_Cparam_init(fiordos6x6_Cparam_Params *params, fiordos6x6_Cparam_Settings *settings, fiordos6x6_Cparam_Result *result, fiordos6x6_Cparam_Work *work);
void fiordos6x6_Cparam_solve(fiordos6x6_Cparam_Params *params, fiordos6x6_Cparam_Settings *settings, fiordos6x6_Cparam_Result *result, fiordos6x6_Cparam_Work *work);
#endif
