/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#ifndef FIORDOS3X3_CPARAM_SOLVER_H
#define FIORDOS3X3_CPARAM_SOLVER_H

#ifdef USE_REALTYPE_SINGLE
  typedef float realtype;
#else
  typedef double realtype;
#endif

/* <<< struct Params >>> */
#if defined(USE_PARAMSMODE_PTR)  && !(defined(MATLAB_MEX_FILE) || defined(RT))
#  define PARAMS_MACRO(name,len) const realtype *name;
#else /* the default */
#  define PARAMS_MACRO(name,len) realtype name[len];
#endif
typedef struct {
    PARAMS_MACRO(H,9)
    PARAMS_MACRO(g,3)
    PARAMS_MACRO(Ai,54)
    PARAMS_MACRO(bi,18)
} fiordos3x3_Cparam_Params;
#undef PARAMS_MACRO

/* <<< struct Settings >>> */
typedef struct {
    struct {
        int warmstartInner;
    } approach;
    struct {
        realtype init[3];
        int maxit;
    } algoInner;
    struct {
        realtype init[18];
        int maxit;
    } algoOuter;
} fiordos3x3_Cparam_Settings;

/* <<< struct Result >>> */
typedef struct {
    realtype la[18];
    realtype x[3];
    realtype d;
    int iter;
    int exitflag;
} fiordos3x3_Cparam_Result;

/* <<< struct Work >>> */
typedef struct {
    struct {
        realtype inner_g[3];
        realtype inner_c[1];
        realtype traceH0[1];
    } Prob;
    struct {
        realtype init[3];
        realtype glob_LbL;
        realtype glob_UbL;
        realtype tstep;
        int btnum;
        realtype tstepmin;
        int btstopped;
        realtype res_z[3];
        int res_stopcode;
        int res_iter;
    } algoInner;
    struct {
        realtype init[18];
        realtype glob_LbL;
        realtype glob_UbL;
        realtype tstep;
        int btnum;
        realtype tstepmin;
        int btstopped;
        realtype res_z[18];
        int res_stopcode;
        int res_iter;
    } algoOuter;
} fiordos3x3_Cparam_Work;

/* <<< solver INTERFACE >>> */
void fiordos3x3_Cparam_init(fiordos3x3_Cparam_Params *params, fiordos3x3_Cparam_Settings *settings, fiordos3x3_Cparam_Result *result, fiordos3x3_Cparam_Work *work);
void fiordos3x3_Cparam_solve(fiordos3x3_Cparam_Params *params, fiordos3x3_Cparam_Settings *settings, fiordos3x3_Cparam_Result *result, fiordos3x3_Cparam_Work *work);
#endif
