/**
 * This file is generated by FiOrdOs, a program licensed under GPL
 * by copyright holder Automatic Control Laboratory, ETH Zurich.
 * 
 * If you are interested in using this file commercially,
 * please contact the copyright holder.
 */

#ifndef FIORDOS4X4_CPARAM_SOLVER_H
#define FIORDOS4X4_CPARAM_SOLVER_H

#ifdef USE_REALTYPE_SINGLE
  typedef float realtype;
#else
  typedef double realtype;
#endif

/* <<< struct Params >>> */
#if defined(USE_PARAMSMODE_PTR)  && !(defined(MATLAB_MEX_FILE) || defined(RT))
#  define PARAMS_MACRO(name,len) const realtype *name;
#else /* the default */
#  define PARAMS_MACRO(name,len) realtype name[len];
#endif
typedef struct {
    PARAMS_MACRO(H,16)
    PARAMS_MACRO(g,4)
    PARAMS_MACRO(Ai,96)
    PARAMS_MACRO(bi,24)
} fiordos4x4_Cparam_Params;
#undef PARAMS_MACRO

/* <<< struct Settings >>> */
typedef struct {
    struct {
        int warmstartInner;
    } approach;
    struct {
        realtype init[4];
        int maxit;
    } algoInner;
    struct {
        realtype init[24];
        int maxit;
    } algoOuter;
} fiordos4x4_Cparam_Settings;

/* <<< struct Result >>> */
typedef struct {
    realtype la[24];
    realtype x[4];
    realtype d;
    int iter;
    int exitflag;
} fiordos4x4_Cparam_Result;

/* <<< struct Work >>> */
typedef struct {
    struct {
        realtype inner_g[4];
        realtype inner_c[1];
        realtype traceH0[1];
    } Prob;
    struct {
        realtype init[4];
        realtype glob_LbL;
        realtype glob_UbL;
        realtype tstep;
        int btnum;
        realtype tstepmin;
        int btstopped;
        realtype res_z[4];
        int res_stopcode;
        int res_iter;
    } algoInner;
    struct {
        realtype init[24];
        realtype glob_LbL;
        realtype glob_UbL;
        realtype tstep;
        int btnum;
        realtype tstepmin;
        int btstopped;
        realtype res_z[24];
        int res_stopcode;
        int res_iter;
    } algoOuter;
} fiordos4x4_Cparam_Work;

/* <<< solver INTERFACE >>> */
void fiordos4x4_Cparam_init(fiordos4x4_Cparam_Params *params, fiordos4x4_Cparam_Settings *settings, fiordos4x4_Cparam_Result *result, fiordos4x4_Cparam_Work *work);
void fiordos4x4_Cparam_solve(fiordos4x4_Cparam_Params *params, fiordos4x4_Cparam_Settings *settings, fiordos4x4_Cparam_Result *result, fiordos4x4_Cparam_Work *work);
#endif
